#!/usr/bin/env bash
# Install the load balancer

# Update software packages
sudo apt-get -y update && sudo apt-get -y upgrade

# Install haproxy
sudo apt-get -y install haproxy

# Setup a proxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 5746-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 5746-web-02 54.90.185.126 check\n\tserver 5746-web-01 54.236.223.57 check" /etc/haproxy/haproxy.cfg

# Start the proxy
sudo service haproxy start
