#!/usr/bin/env bash
# Installing nginx on a server and configuring a simple server

sudo apt-get update
sudo apt-get install nginx -y
sudo mkdir /var/www/html
sudo touch /var/www/html/index.html
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
